"""add negotiation rounds and trade round tracking

Revision ID: 48110d56fe6f
Revises: 6947cdf0a775
Create Date: 2026-09-28 05:11:56.598089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48110d56fe6f'
down_revision: Union[str, Sequence[str], None] = '6947cdf0a775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_offers_household_id'), 'negotiation_offers', ['household_id'], unique=False)
    op.create_index(op.f('ix_negotiation_offers_tick_index'), 'negotiation_offers', ['tick_index'], unique=False)
    # server_default in case any trade rows already exist — see the
    # equivalent comment on the households.battery_soc migration.
    op.add_column(
        'trades', sa.Column('round_index', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'round_index')
    op.drop_index(op.f('ix_negotiation_offers_tick_index'), table_name='negotiation_offers')
    op.drop_index(op.f('ix_negotiation_offers_household_id'), table_name='negotiation_offers')
    op.drop_table('negotiation_offers')
    # ### end Alembic commands ###
