"""create households table and link users

Revision ID: 64ef1ec05d3a
Revises: 2d17e48fa71a
Create Date: 2026-09-28 04:14:29.173779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ef1ec05d3a'
down_revision: Union[str, Sequence[str], None] = '2d17e48fa71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('solar_capacity_kwp', sa.Float(), nullable=False),
    sa.Column('battery_capacity_kwh', sa.Float(), nullable=False),
    sa.Column('battery_max_charge_kw', sa.Float(), nullable=False),
    sa.Column('battery_max_discharge_kw', sa.Float(), nullable=False),
    sa.Column('evening_reserve', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('household_id', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_users_household_id', 'users', ['household_id'])
    op.create_foreign_key(
        'fk_users_household_id_households', 'users', 'households', ['household_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_household_id_households', 'users', type_='foreignkey')
    op.drop_constraint('uq_users_household_id', 'users', type_='unique')
    op.drop_column('users', 'household_id')
    op.drop_table('households')
    # ### end Alembic commands ###
