"""add simulation tables and household battery soc

Revision ID: 6947cdf0a775
Revises: 64ef1ec05d3a
Create Date: 2026-09-28 04:31:14.855264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6947cdf0a775'
down_revision: Union[str, Sequence[str], None] = '64ef1ec05d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('running', sa.Boolean(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('seconds_per_tick', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curtailments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('buyer_household_id', sa.String(length=20), nullable=False),
    sa.Column('seller_household_id', sa.String(length=20), nullable=False),
    sa.Column('curtailed_kwh', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['seller_household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curtailments_buyer_household_id'), 'curtailments', ['buyer_household_id'], unique=False)
    op.create_index(op.f('ix_curtailments_seller_household_id'), 'curtailments', ['seller_household_id'], unique=False)
    op.create_index(op.f('ix_curtailments_tick_index'), 'curtailments', ['tick_index'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('buyer_household_id', sa.String(length=20), nullable=False),
    sa.Column('seller_household_id', sa.String(length=20), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['seller_household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_ledger_entries_buyer_household_id'), 'ledger_entries', ['buyer_household_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_seller_household_id'), 'ledger_entries', ['seller_household_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_tick_index'), 'ledger_entries', ['tick_index'], unique=False)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.String(length=20), nullable=False),
    sa.Column('consumption_kw', sa.Float(), nullable=False),
    sa.Column('generation_kw', sa.Float(), nullable=False),
    sa.Column('battery_soc', sa.Float(), nullable=False),
    sa.Column('battery_action', sa.String(length=20), nullable=False),
    sa.Column('grid_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_household_id'), 'meter_readings', ['household_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_tick_index'), 'meter_readings', ['tick_index'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tick_index', sa.Integer(), nullable=False),
    sa.Column('buyer_household_id', sa.String(length=20), nullable=False),
    sa.Column('seller_household_id', sa.String(length=20), nullable=False),
    sa.Column('kwh', sa.Float(), nullable=False),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['seller_household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_buyer_household_id'), 'trades', ['buyer_household_id'], unique=False)
    op.create_index(op.f('ix_trades_seller_household_id'), 'trades', ['seller_household_id'], unique=False)
    op.create_index(op.f('ix_trades_tick_index'), 'trades', ['tick_index'], unique=False)
    # server_default so the ALTER succeeds against the households already
    # seeded before this migration existed; sqlalchemy.Mapped's `default` is
    # applied only on INSERT through the ORM, never by the database itself.
    op.add_column(
        'households',
        sa.Column('battery_soc', sa.Float(), nullable=False, server_default='0.5'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('households', 'battery_soc')
    op.drop_index(op.f('ix_trades_tick_index'), table_name='trades')
    op.drop_index(op.f('ix_trades_seller_household_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_buyer_household_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_meter_readings_tick_index'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_household_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_ledger_entries_tick_index'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_seller_household_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_buyer_household_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_curtailments_tick_index'), table_name='curtailments')
    op.drop_index(op.f('ix_curtailments_seller_household_id'), table_name='curtailments')
    op.drop_index(op.f('ix_curtailments_buyer_household_id'), table_name='curtailments')
    op.drop_table('curtailments')
    op.drop_table('simulation_state')
    # ### end Alembic commands ###
